baseURL: "https://www.yatanco.com" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Yatan Blumenthal Vargas
paginate: 10
theme: PaperMod

#theme params
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

# Languages and Menu
languages:
# English Version
    en:
        languageName: ":uk:"
        languageAltTitle: "English"
        weight: 1
        taxonomies:
         category: categories
         tag: tags
         series: series

        menu:
            main:
                - name: Emotional Intelligence
                  url: emotional-intelligence
                  weight: 5
              #  - name: Archive
              #    url: archives
              #    weight: 5
                - name: Blog
                  url: posts/
                  weight: 5
                - name: Projects
                  url: project/
                  weight: 5
               # - name: Meditation
               #   url: meditation/
               #   weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

          
  # Spanish Version
    es:
        languageName: ":es:"
        languageAltTitle: "Spanish"
        weight: 2
        title: Yatan Blumenthal Vargas
        taxonomies:
          category: categorias
          tag: tags
          series: series
          
        profileMode:
            enabled: true
            title: Hola!
            imageUrl: "images/yatan-logo.webp" # optional
            imageTitle: "Yatan Blumenthal Vargas Riendose" # optional
            imageWidth: 200 # custom size
            imageHeight: 200 # custom size
            subtitle: "Yo soy Yatan. Yo le ayudo a startups por medio de [Founder Institute](https://fi.co) y [Hardware.co](https://hardware.co).
            Le ayudo a equipos tener mejor culturay comunicacion por medio de [Culture Design](https://culturedesign.org) & [Search Inside Yourself](http://siyli.org). 
            Invierto en Startups por medio de [Infinita VC](https://infinitafund.com). "
            buttons:
                - name: Blog
                  url: posts/
                - name: Tags
                  url: Temas
        menu:
            main:
                - name: Sobre Mi
                  url: project
                  weight: 5
              #  - name: Archive
              #    url: archives
              #    weight: 5
                - name: Blog
                  url: posts/
                  weight: 5
               # - name: My Work
               #  url: work/
               #   weight: 5
               # - name: Meditation
               #   url: meditation/
               #   weight: 5
                - name: Busqueda
                  url: search/
                  weight: 10
                - name: Temas
                  url: tags
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Yatan - https://github.com/adityatelange/hugo-PaperMod"
    author: Yatan
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    # English option (main)

    profileMode:
        enabled: true
        title: "Hola,Hello,Hey!" # optional default will be site title
        subtitle: "I am Yatan. I support startups through [Founder Institute](https://fi.co) and [Hardware.co](https://hardware.co).
        Work for better team culture and communication through [Culture Design](https://culturedesign.org) & [Search Inside Yourself](http://siyli.org). 
        And I invest through [Infinita VC](https://infinitavc.com). "
        imageUrl: "images/yatan-logo.webp" # optional
        imageTitle: "Yatan Blumenthal Vargas Pic" # optional
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size

        buttons:
            - name: My Work
              url: project
            - name: Meditations
              url: http://insighttimer.com/yatan
            - name: Blog
              url: posts
            - name: Book a call 
              url: http://calendly.com/yatan/
  
      
    homeInfoParams:
        Title: "Yatan Blumenthal Vargas"
        Content: 
          # Running Shit 
          Hello, I am Yatan. I like to support startups through accelerator teams like [Founder Institute](https://fi.co) and [Hardware.co](https://fi.co),
          build better teams through [Culture Design](https://culturedesign.org) and train people in emotional intelligence as a [Search Inside Yourself](http://siyli.org). 
         
         I like to write about   

         

         
    socialIcons:
        - name: github
          url: "https://github.com/yatanco/"
        - name: linkedin
          url: "http://linkedin.com/in/yatanblumenthal"
        - name: RSS
          url: "index.xml"

    editPost:
        URL: "https://github.com/yatanco/yatanco.com"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
          favicon: "/assets/yatan-favicon.ico"
         #favicon16x16: "/assets/yatan-favicon.ico"
         #favicon32x32: "/assets/yatan-favicon.ico"
         #apple_touch_icon: "/assets/yatan-favicon.ico"
         #safari_pinned_tab: "/assets/yatan-favicon.ico"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
